module Swank
  module Decorators
    class DecorationInjector
      module MethodAddedHooks
        def method_added: (Symbol method_name) -> void

        def singleton_method_added: (Symbol method_name) -> void

        private

        def decoration_injector: () -> Swank::Decorators::DecorationInjector
      end

      attr_reader subject: Class | Module

      attr_reader queued_decorations: Swank::Decorators::DecoratorBase

      def self.bind: (Class | Module subject) -> Swank::Decorators::DecorationInjector

      def initialize: (Class | Module subject) -> void

      def queue_decoration: (Symbol decorator_name, *untyped args, **untyped kwargs) ?{ () -> untyped } -> Swank::Decorators::DecoratorBase

      def inject_decorations!: (Symbol method_name, mode: Symbol) -> void

      def register_decorators!: (Swank::Decorators decorators_module) -> void

      def decorators: () -> Hash[Symbol, Class]

      def define_decorator_methods!: (Symbol decorator_name) -> void

      private

      type decoration_injection_base_module_type = singleton(Swank::Decorators::DecorationInjection::InstanceLevel) | singleton(Swank::Decorators::DecorationInjection::SingletonLevel)

      def fetch_decorator_injection_module: (
        decoration_injection_base_module_type base_module
      ) -> singleton(Swank::Decorators::DecorationInjection::InstanceLevel)

      def decoration_injection_base_module: (Symbol scope) -> decoration_injection_base_module_type 

      def register_decorator!: (Symbol decorator_name, singleton(Swank::Decorators::DecoratorBase) decorator_class) -> void
    end
  end
end
