module Swank
  module Decorators
    class DecoratorWithContext < DecoratorBase
      @args: Array

      @kwargs: Hash

      @block: Proc | nil

      NOTHING: Object

      def self.setup: (Symbol decorator_name, Proc wrap_block) -> untyped

      NOTHING_STRING: "::Swank::Decorators::DecoratorWithContext::NOTHING"

      def self.initialize_parameter_string: () -> String

      def self.initialize_variable_set_string: () -> String

      attr_reader args: Array
      
      attr_reader kwargs: Hash

      attr_reader block: Proc | nil

      def initialize: (*untyped args, **untyped kwargs) { () -> untyped } -> void

      def wrap_block: () -> Proc
    end
  end
end
