module Swank
  module Decorators
    class IvarDsl
      @decorator_name: Symbol

      @injector: Swank::Decorators::DecorationInjector

      attr_reader decorator_name: Symbol

      attr_reader injector: Swank::Decorators::DecorationInjector

      def initialize: (Symbol decorator_name, Swank::Decorators::DecorationInjector injector) -> void

      def call: (*untyped) ?{ (*untyped) -> untyped } -> Swank::Decorators::DecoratorBase

      def []: (*untyped) ?{ (*untyped, **untyped) -> untyped } -> Swank::Decorators::DecoratorBase

      def +@: () -> Swank::Decorators::DecoratorBase

      alias ! +@

      def >>: (untyped other) -> Swank::Decorators::DecoratorBase

      alias >= >>
    end
  end
end
