name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.0'
          - '3.1.0'
          - '3.2.0'
          - '3.3.0'
          - '3.4.0'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    name: Linter - StandardRB
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true
      - name: Run Linter
        run: bundle exec standardrb
